---
- hosts: all
  tasks:
    - name: Service Key
      tags: [all]
      quay_service_key:
        state: present
        name: key1
        key: abcdef1234
      register: params
    - name: Upload Service Key
      tags: [all]
      uri:
        url: "{{ quay_url }}/service_key"
        validate_certs: no
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ params }}"
        body_format: json
      register: result
