---
- hosts: all
  tasks:
    # D A T A B A S E
    #
    - name: Reset Database
      tags: [reset]
      quay_database:
        state: reset
      register: params
    - name: Validate Database
      tags: [all, database]
      quay_database:
        state: present
      register: params
    - name: Upload Database
      tags: [all, database, reset]
      uri:
        url: "{{ quay_url }}/database"
        # This doesn't work
        # client_cert: /home/thomasmckay/code/tmp/ssl.cert
        # client_key: /home/thomasmckay/code/tmp/ssl.key
        validate_certs: no
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ params }}"
        body_format: json
      register: result
